server {
    listen 443 ssl http2;
    server_name ipsec.dynu.net;

    ssl_certificate     /root/.acme.sh/ipsec.dynu.net_ecc/fullchain.cer;
    ssl_certificate_key /root/.acme.sh/ipsec.dynu.net_ecc/ipsec.dynu.net.key;

    location /xhttp {
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:8443;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}
root@ip-172-31-47-12:/home/ubuntu# cat /etc/nginx/sites-available/xhttp.conf
server {
    listen 443 ssl http2;
    server_name ipsec.dynu.net;

    ssl_certificate     /root/.acme.sh/ipsec.dynu.net_ecc/fullchain.cer;
    ssl_certificate_key /root/.acme.sh/ipsec.dynu.net_ecc/ipsec.dynu.net.key;

    location /xhttp {
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:8443;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}